apiVersion: v1
kind: Template
metadata:
  name: "jenkins-deployment-automation"
  annotations:
    openshift.io/display-name: JenkinsOpenshift
    iconClass: fa fa-code
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: "jenkins-deployment-automation"
      name: "jenkins-deployment-automation"
    spec:
      to:
        kind: Service
        name: "jenkins-deployment-automation"